.TH CANDUMP 8 "13 March 2005" "canutils" "Linux Programmer's Manual"
.SH NAME
candump \- dump messages from CAN bus interfaces to stdout
.SH SYNOPSIS
.B "candump <interface> [Options]"
.br
.SH DESCRIPTION
candump receives messages from a CAN (Controller Area Network) bus
interface and dumps it to stdout. 

.SH ARGUMENTS and OPTIONS
.TP
.B interface
The name of the interface. This is usually a driver name followed by
a unit number, for example "can0". 
.TP
.B -f family
Specifies the protocol family which has to be sniffed for. Default is
PF_CAN, which is 30. 
.TP
.B -t type 
Specifies the socket type to be sniffed on. Default is SOCK_RAW, which
is 3. 
.TP
.B -p proto
Specifies the protocol to sniff for; default is CAN_PROTO_RAW, which is
0. 
.br
.SH SEE ALSO
- ifconfig(8), canconfig(8), canecho(8)
.br
- http://www.pengutronix.de/software/socket-can/ (Socket-CAN Project)
.SH AUTHORS
Marc Kleine-Budde <m.kleine-budde@pengutronix.de>
Robert Schwebel <r.schwebel@pengutronix.de>
