.TH CANECHO 8 "13 March 2005" "canutils" "Linux Programmer's Manual"
.SH NAME
canecho \- loop back received CAN messages to the interface
.SH SYNOPSIS
.B "canecho <interface> [Options]"
.br
.SH DESCRIPTION
canecho receives messages from a CAN (Controller Area Network) bus
interface and directly sends the message back to the same interface.
This can be used to test a remote CAN node by sending messages and
testing if the same messages are being echoed back.  

.SH ARGUMENTS and OPTIONS
.TP
.B interface
The name of the interface. This is usually a driver name followed by
a unit number, for example "can0". 
.TP
.B -f family
Specifies the protocol family which has to be sniffed for. Default is
PF_CAN, which is 30. 
.TP
.B -t type 
Specifies the socket type to be sniffed on. Default is SOCK_RAW, which
is 3. 
.TP
.B -p proto
Specifies the protocol to sniff for; default is CAN_PROTO_RAW, which
is 0.
.TP
.B -v
Verbose mode. 
0. 
.br
.SH SEE ALSO
- ifconfig(8), canconfig(8), candump(8), cansend(8)
.br
- http://www.pengutronix.de/software/socket-can/ (Socket-CAN Project)
.SH AUTHORS
Marc Kleine-Budde <m.kleine-budde@pengutronix.de>
Robert Schwebel <r.schwebel@pengutronix.de>
